"""initial chat workspace schema"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("users", sa.Column("id", sa.String(36), primary_key=True), sa.Column("email", sa.String(320), nullable=False), sa.Column("display_name", sa.String(120), nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(20), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("email"))
    op.create_index("ix_users_email", "users", ["email"]); op.create_index("ix_users_role", "users", ["role"]); op.create_index("ix_users_status", "users", ["status"])
    op.create_table("model_channels", sa.Column("id", sa.String(36), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("provider", sa.String(80), nullable=False), sa.Column("protocol", sa.String(30), nullable=False), sa.Column("base_url", sa.String(500), nullable=False), sa.Column("api_key_encrypted", sa.Text(), nullable=False), sa.Column("modality", sa.String(20), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False), sa.Column("priority", sa.Integer(), nullable=False), sa.Column("models_json", sa.JSON(), nullable=False), sa.Column("created_by", sa.String(36)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("name"))
    op.create_index("ix_model_channels_name", "model_channels", ["name"]); op.create_index("ix_model_channels_modality", "model_channels", ["modality"]); op.create_index("ix_model_channels_enabled", "model_channels", ["enabled"])
    op.create_table("refresh_tokens", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("token_hash", sa.String(128), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("token_hash"))
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"]); op.create_index("ix_refresh_tokens_token_hash", "refresh_tokens", ["token_hash"])
    op.create_table("entitlements", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("granted_by", sa.String(36)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_entitlements_user_id", "entitlements", ["user_id"]); op.create_index("ix_entitlements_status", "entitlements", ["status"])
    op.create_table("projects", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("description", sa.String(500), nullable=False), sa.Column("archived_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_projects_user_id", "projects", ["user_id"])
    op.create_table("threads", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", sa.String(36), sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("title", sa.String(200), nullable=False), sa.Column("model", sa.String(120), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("archived_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_threads_user_id", "threads", ["user_id"]); op.create_index("ix_threads_project_id", "threads", ["project_id"]); op.create_index("ix_threads_status", "threads", ["status"])
    op.create_table("messages", sa.Column("id", sa.String(36), primary_key=True), sa.Column("thread_id", sa.String(36), sa.ForeignKey("threads.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("role", sa.String(20), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("content_type", sa.String(20), nullable=False), sa.Column("sequence", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_messages_thread_id", "messages", ["thread_id"]); op.create_index("ix_messages_user_id", "messages", ["user_id"])
    op.create_table("assets", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("message_id", sa.String(36), sa.ForeignKey("messages.id", ondelete="SET NULL")), sa.Column("kind", sa.String(30), nullable=False), sa.Column("storage_key", sa.String(500), nullable=False), sa.Column("mime_type", sa.String(120), nullable=False), sa.Column("size_bytes", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_assets_user_id", "assets", ["user_id"])
    op.create_table("model_requests", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("thread_id", sa.String(36), sa.ForeignKey("threads.id", ondelete="SET NULL")), sa.Column("message_id", sa.String(36), sa.ForeignKey("messages.id", ondelete="SET NULL")), sa.Column("channel_id", sa.String(36), sa.ForeignKey("model_channels.id", ondelete="SET NULL")), sa.Column("model", sa.String(120), nullable=False), sa.Column("modality", sa.String(20), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("input_tokens", sa.Integer()), sa.Column("output_tokens", sa.Integer()), sa.Column("provider_request_id", sa.String(200)), sa.Column("latency_ms", sa.Integer()), sa.Column("error_code", sa.String(100)), sa.Column("usage_json", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_model_requests_user_id", "model_requests", ["user_id"]); op.create_index("ix_model_requests_thread_id", "model_requests", ["thread_id"]); op.create_index("ix_model_requests_status", "model_requests", ["status"]); op.create_index("ix_model_requests_created_at", "model_requests", ["created_at"])
    op.create_table("exports", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("thread_id", sa.String(36), sa.ForeignKey("threads.id", ondelete="CASCADE"), nullable=False), sa.Column("format", sa.String(20), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("storage_key", sa.String(500)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_exports_user_id", "exports", ["user_id"]); op.create_index("ix_exports_thread_id", "exports", ["thread_id"])
    op.create_table("admin_audit_logs", sa.Column("id", sa.String(36), primary_key=True), sa.Column("admin_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("action", sa.String(120), nullable=False), sa.Column("target_user_id", sa.String(36)), sa.Column("metadata_json", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_admin_audit_logs_admin_id", "admin_audit_logs", ["admin_id"]); op.create_index("ix_admin_audit_logs_target_user_id", "admin_audit_logs", ["target_user_id"]); op.create_index("ix_admin_audit_logs_created_at", "admin_audit_logs", ["created_at"])


def downgrade():
    for table in ["admin_audit_logs", "exports", "model_requests", "assets", "messages", "threads", "projects", "entitlements", "refresh_tokens", "model_channels", "users"]:
        op.drop_table(table)
