import { FormEvent, useState } from 'react'
import { ArrowLeft, Folder, MessageSquare, Plus } from 'lucide-react'

type Project = { id: string; name: string; description: string; thread_count: number }

export default function ProjectWorkspacePage({ projects, onBack, onCreateProject, onCreateThread }: { projects: Project[]; onBack: () => void; onCreateProject: (name: string, description: string) => Promise<void>; onCreateThread: (projectId: string) => void }) {
  const [creating, setCreating] = useState(false); const [name, setName] = useState(''); const [description, setDescription] = useState('')
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; await onCreateProject(name.trim(), description.trim()); setName(''); setDescription(''); setCreating(false) }
  return <section className="workspace-page project-workspace"><header><button className="icon-button" aria-label="返回对话" onClick={onBack}><ArrowLeft size={19} /></button><h1>项目</h1><button className="workspace-primary" onClick={() => setCreating(true)}><Plus size={17} />新建项目</button></header><p className="workspace-subtitle">在项目中整理相关对话，让每项工作拥有独立上下文。</p>{creating && <form className="project-create-form" onSubmit={submit}><label>项目名称<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="例如：品牌视觉方案" /></label><label>描述 <small>可选</small><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="这个项目用于什么工作？" /></label><div><button type="button" className="secondary-button" onClick={() => setCreating(false)}>取消</button><button type="submit" className="workspace-primary"><Plus size={15} />创建项目</button></div></form>}<div className="project-grid">{projects.map((project) => <article className="project-card" key={project.id}><div className="project-card-icon"><Folder size={19} /></div><div className="project-card-body"><h2>{project.name}</h2><p>{project.description || '暂无描述'}</p><span><MessageSquare size={13} />{project.thread_count} 个对话</span></div><button className="icon-button" title="在项目中新建对话" aria-label="在项目中新建对话" onClick={() => onCreateThread(project.id)}><Plus size={18} /></button></article>)}{!projects.length && !creating && <div className="project-empty"><Folder size={28} /><h2>还没有项目</h2><p>创建第一个项目，集中管理对话。</p><button className="secondary-button" onClick={() => setCreating(true)}><Plus size={16} />新建项目</button></div>}</div></section>
}
